MAL_TOP100 = [
    ("Sousou no Frieren", "sousou-no-frieren"),
    ("Re:Zero kara Hajimeru Isekai Seikatsu 4th Season", "re-zero-kara-hajimeru-isekai-seikatsu-4th-season"),
    ("Fullmetal Alchemist: Brotherhood", "fullmetal-alchemist-brotherhood"),
    ("Steel Ball Run: JoJo no Kimyou na Bouken", "jojo-no-kimyou-na-bouken"),
    ("Steins;Gate", "steins-gate"),
    ("Chainsaw Man Movie: Reze-hen", "chainsaw-man"),
    ("Gintama: The Final", "gintama-the-final"),
    ("Gintama", "gintama"),
    ("Shingeki no Kyojin Season 3 Part 2", "shingeki-no-kyojin-season-3-part-2"),
    ("Hunter x Hunter (2011)", "hunter-x-hunter"),
    ("Ginga Eiyuu Densetsu", "ginga-eiyuu-densetsu"),
    ("Gintama'", "gintama-2015"),
    ("Gintama': Enchousen", "gintama"),
    ("One Piece Fan Letter", "one-piece"),
    ("Mushoku Tensei III: Isekai Ittara Honki Dasu", "mushoku-tensei-iii-isekai-ittara-honki-dasu"),
    ("Bleach: Sennen Kessen-hen", "bleach-sennen-kessen-hen"),
    ("Gintama.", "gintama-2017"),
    ("Kaguya-sama wa Kokurasetai: Ultra Romantic", "kaguya-sama-wa-kokurasetai-ultra-romantic"),
    ("Clannad: After Story", "clannad-after-story"),
    ("Fruits Basket: The Final", "fruits-basket-2019"),
    ("Gintama", "gintama"),
    ("Koe no Katachi", "koe-no-katachi"),
    ("Code Geass: Hangyaku no Lelouch R2", "code-geass-hangyaku-no-lelouch-r2"),
    ("Kusuriya no Hitorigoto 2nd Season", "kusuriya-no-hitorigoto"),
    ("3-gatsu no Lion 2nd Season", "3-gatsu-no-lion"),
    ("Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare", "gintama"),
    ("Monster", "monster"),
    ("Gintama. Shirogane no Tamashii-hen - Kouhan-sen", "gintama-2017"),
    ("Owarimonogatari 2nd Season", "owarimonogatari-2nd-season"),
    ("Shingeki no Kyojin: The Final Season: Kanketsu-hen", "shingeki-no-kyojin-the-final-season"),
    ("Sousou no Frieren 2nd Season", "sousou-no-frieren-2nd-season"),
    ("Kingdom 3rd Season", "kingdom"),
    ("Kusuriya no Hitorigoto", "kusuriya-no-hitorigoto"),
    ("Vinland Saga Season 2", "vinland-saga-season-2"),
    ("Violet Evergarden Movie", "violet-evergarden"),
    ("Kimi no Na wa.", "kimi-no-na-wa"),
    ("Ashita no Joe 2", "ashita-no-joe"),
    ("Gintama. Shirogane no Tamimii-hen", "gintama-2017"),
    ("Shingeki no Kyojin: The Final Season", "shingeki-no-kyojin-the-final-season"),
    ("Hajime no Ippo", "hajime-no-ippo"),
    ("Kizumonogatari III: Reiketsu-hen", "kizumonogatari-iii-reiketsu-hen"),
    ("Mob Psycho 100 II", "mob-psycho-100-ii"),
    ("Vinland Saga", "vinland-saga"),
    ("Haikyuu!! Karasunou Koukou vs. Shiratorizawa Gakuen Koukou", "haikyuu"),
    ("Sen to Chihiro no Kamikakushi", "sen-to-chihiro-no-kamikakushi"),
    ("Shingeki no Kyojin: The Final Season Part 2", "shingeki-no-kyojin-the-final-season-part-2"),
    ("Monogatari Series: Second Season", "monogatari-series-second-season"),
    ("Cowboy Bebop", "cowboy-bebop"),
    ("Takopii no Genzai", "takopii-no-genzai"),
    ("86 Part 2", "86-2nd-season"),
    ("Bocchi the Rock!", "bocchi-the-rock"),
    ("Guimi Zhi Zhu Specials", None),
    ("Hibike! Euphonium 3", "hibike-euphonium"),
    ("Ikoku Nikki", "ikoku-nikki"),
    ("Kingdom 4th Season", "kingdom"),
    ("One Piece", "one-piece"),
    ("Chi. Chikyuu no Undou ni Tsuite", "chi-chikyuu-no-undou-ni-tsuite"),
    ("Kingdom 5th Season", "kingdom"),
    ("Mob Psycho 100 III", "mob-psycho-100-iii"),
    ("Mushishi Zoku Shou 2nd Season", "mushishi"),
    ("Boku no Hero Academia: Final Season", "boku-no-hero-academia-final-season"),
    ("Code Geass: Hangyaku no Lelouch", "code-geass-hangyaku-no-lelouch"),
    ("Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai", "kaguya-sama-wa-kokurasetai-first-kiss-wa-owaranai"),
    ("Bleach: Sennen Kessen-hen: Ketsubetsu-tan", "bleach-sennen-kessen-hen-ketsubetsu-tan"),
    ("Jujutsu Kaisen 2nd Season", "jujutsu-kaisen"),
    ("Shiguang Dailiren", None),
    ("Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen", "shouwa-genroku-rakugo-shinjuu"),
    ("The First Slam Dunk", "slam-dunk-movie"),
    ("Kimetsu no Yaiba: Yuukaku-hen", "kimetsu-no-yaiba-yuukaku-hen"),
    ("Mushishi Zoku Shou", "mushishi"),
    ("Rurouni Kenshin: Meiji Kenkaku Romantan: Tsuioku-hen", "rurouni-kenshin-meiji-kenkaku-romantan"),
    ("Violet Evergarden", "violet-evergarden"),
    ("[Oshi no Ko] 3rd Season", "oshi-no-ko"),
    ("Bleach: Sennen Kessen-hen: Soukoku-tan", "bleach-sennen-kessen-hen-soukoku-tan"),
    ("Boku no Kokoro no Yabai Yatsu 2nd Season", "boku-no-kokoro-no-yabai-yatsu"),
    ("Great Teacher Onizuka", "great-teacher-onizuka"),
    ("Hajime no Ippo: New Challenger", "hajime-no-ippo"),
    ("Howl no Ugoku Shiro", "howl-no-ugoku-shiro"),
    ("Kingdom 6th Season", "kingdom"),
    ("Mononoke Hime", "mononoke-hime"),
    ("Tu Bian Yingxiong X", "tu-bian-yingxiong-x"),
    ("Uma Musume: Cinderella Gray Part 2", "uma-musume-pretty-derby"),
    ("Kimetsu no Yaiba Movie 1: Mugenjou-hen: Akaza Sairai", "kimetsu-no-yaiba-yuukaku-hen"),
    ("Luo Xiaohei Zhanji 2", None),
    ("Mo Dao Zu Shi: Wanjie Pian", "mo-dao-zu-shi"),
    ("Mushishi", "mushishi"),
    ("Shingeki no Kyojin Season 3", "shingeki-no-kyojin-season-3"),
    ("Monogatari Series: Off & Monster Season", "monogatari-series-off-monster-season"),
    ("Shigatsu wa Kimi no Uso", "shigatsu-wa-kimi-no-uso"),
    ("Tengen Toppa Gurren Lagann", "tengen-toppa-gurren-lagann"),
    ("Tian Guan Cifu Er", "tian-guan-cifu-er"),
    ("Uma Musume: Pretty Derby: Shin Jidai no Tobira", "uma-musume-pretty-derby"),
    ("Fate/stay night Movie: Heaven's Feel: III. Spring Song", "fate-stay-night"),
    ("Natsume Yuujinchou Shi", "natsume-yuujinchou"),
    ("Odd Taxi", "odd-taxi"),
    ("Ping Pong the Animation", "ping-pong-the-animation"),
    ("Cyberpunk: Edgerunners", "cyberpunk-edgerunners"),
    ("Death Note", "death-note"),
    ("Haikyuu!! Movie: Gomisuteba no Kessen", "haikyuu"),
]